# See https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md
# and https://github.com/DavidAnson/markdownlint-cli2

config:
  ul-style: false
  line-length: false
  no-duplicate-heading:
    siblings_only: true
  ol-prefix:
    style: ordered
  no-inline-html: false
  fenced-code-language: false
  no-trailing-punctuation:
    punctuation: ".,;:" # allowing exclamation points and question marks at end of sentences

ignores:
  - "**/build/**"
  - "**/node_modules/**"
  - "CHANGELOG.md"
  - "ibm-mq-metrics/docs/metrics.md"
  - ".github/pull_request_template.md"
