version: '3'
services:
  app:
    build:
      context: ../../
      dockerfile: cel-sampler/oats/Dockerfile
    environment:
      OTEL_SERVICE_NAME: "cel-sampler-test-app"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://lgtm:4318
      OTEL_EXPERIMENTAL_CONFIG_FILE: ./otel-config.yaml
    ports:
      - "8080:8080"
