name: Build Daily

on:
  workflow_dispatch:
  schedule:
    # Run daily at 7:30 AM UTC
    - cron: '30 7 * * *'

permissions:
  contents: read

jobs:
  common:
    uses: ./.github/workflows/build-common.yml
    with:
      no-build-cache: true
    secrets:
      DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}

  link-check:
    uses: ./.github/workflows/reusable-link-check.yml

  publish-snapshots:
    needs:
      - common
    runs-on: ubuntu-latest
    if: github.ref_name == 'main' && github.repository == 'open-telemetry/opentelemetry-java-contrib'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up JDK for running Gradle
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: temurin
          java-version: 21

      - name: Set up gradle
        uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c # v5.0.2

      - name: Build and publish snapshots
        # Disable parallel due to Sonatype's HTTP 429 rate limiting
        run: ./gradlew assemble publishToSonatype --no-parallel
        env:
          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
          SONATYPE_KEY: ${{ secrets.SONATYPE_KEY }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
          DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ github.token }}

  workflow-notification:
    permissions:
        contents: read
        issues: write
    if: always()
    needs:
      - common
      - link-check
      - publish-snapshots
    uses: ./.github/workflows/reusable-workflow-notification.yml
    with:
      success: >-
        ${{
          needs.common.result == 'success' &&
          needs.link-check.result == 'success' &&
          needs.publish-snapshots.result == 'success'
        }}
