name: Reusable - Misspell check

on:
  workflow_call:

permissions:
  contents: read

jobs:
  misspell-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install misspell
        env:
          # renovate: datasource=github-releases depName=golangci/misspell
          MISSPELL_VERSION: v0.7.0
        run: |
          curl -sfL https://raw.githubusercontent.com/golangci/misspell/${MISSPELL_VERSION}/install-misspell.sh \
            | sh -s -- -b bin ${MISSPELL_VERSION}

      - name: Run misspell
        run: bin/misspell -error .
